### ISSUE TITLE
popup opens  if KEY_TO_CALL_POPUP is continuously pressed instead of double tap

### ISSUE THREAD

**Issue by robatte** [Disablak/quick_script_change#1]
if you change line 43 from:
`		if key_event.keycode == KEY_TO_CALL_POPUP and key_event.is_pressed():`
to:
`		if key_event.keycode == KEY_TO_CALL_POPUP and !key_event.is_pressed():`

it works as intended.

**Comment by Disablak** [comment]
@robatte thanks for suggestion, I fixed it
